name: alpharing-CI-CD

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: '3.10'
        install-type: ['user', 'developer']

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: alpharing
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      - if: matrix.install-type == 'user'
        run: |
          pip install alpharing
          pip install jaxlib==0.4.25+cuda11.cudnn86 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html 

      - if: matrix.install-type == 'developer'
        run: |
          pip install -e .
          pip install jaxlib==0.4.25+cuda11.cudnn86 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
          pip install -e alphafold --no-deps

      - run: |
          pip install pytest
          pytest tests/
