name: alpharing-CI-CD

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: alpharing
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
      
      - name: Install AlphaRING
        run: |
          pip install -e .
      
      - name: Run AlphaRING tests
        run: |
          pip install pytest
          pytest tests/
